# Generated by Django 5.0.6 on 2024-08-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_orders_orderupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
